# fly.toml app configuration file generated for lightsoff-scheduler on 2024-09-06T09:35:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lightsoff-scheduler'
primary_region = 'waw'

[build]

[[vm]]
  size = 'shared-cpu-2x'

[[env]]
  TELEGRAM_CHANNEL = "@lvivoblenergo"
  LOG_LEVEL = "INFO"